#!/bin/bash
set -eu
SITE_DIR=_site

VERSION=$(git rev-parse --short HEAD)
REMOTE_URL=$(git config --get remote.origin.url)

rm -rf ${SITE_DIR}/.git
touch $SITE_DIR/.nojekyll

git init ${SITE_DIR}
git -C ${SITE_DIR} checkout --orphan gh-pages
git -C ${SITE_DIR} add .
git -C ${SITE_DIR} commit --no-verify -m "Update docs for version ${VERSION}"
git -C ${SITE_DIR} remote add origin -m "gh-pages" ${REMOTE_URL}
git -C ${SITE_DIR} push --force -u origin gh-pages
